name: Hola Mundo Workflow

on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  second_job:
    if: ${{ github.event_name == 'push' }}
    # Este job se ejecuta solo si el evento es un push
    # y depende de que el primer job se complete con éxito
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo segundo job"