Hola: Hola mundo
Adios: Adios mundo

personalidad:
  nombre: Juan
  edad: 30
  ciudad: Madrid
  ocupacion: Ingeniero

persona:
  nombre: Juan
  edad: 30
  ciudad: Madrid
  ocupacion: Ingeniero
  intereses:
    - Programación
    - Música
    - Viajes
  habilidades:
    - Python
    - JavaScript
    - SQL
  experiencia_laboral:
    - Empresa: ABC
      Puesto: Desarrollador
      Fecha: 2020-2022

scripts:>
  - nombre: script1
    descripcion: Este es el primer script
    comandos:
      - echo "Hola mundo"
      - ls -l

scripts:|
  - nombre: script2
    descripcion: Este es el segundo script
    comandos:
      - echo "Adios mundo"
      - pwd