name: Hola Mundo Workflow

on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest

    outputs:
      # Esta salida se puede usar en otros jobs
      salida: hola mundo

    env:
      # Variables de entorno que se pueden usar en todo el job
      FIRST_NAME: "Angel"
      LAST_NAME: "Roman"
    # Este job se ejecuta en un entorno Ubuntu
    steps:

      - name: Working dir
        id: steps_1
        run: echo "my_variable=Hola Mundo"
      
      - name: Mostrar variables de entorno
        run: echo "FIRST_NAME is ${{ env.FIRST_NAME }} and LAST_NAME is ${{ env.LAST_NAME }}"

      - name: Mostrar variable de entorno personalizada
        run: echo "${{steps.steps_1.outputs.my_variable}}"

        
  second_job:
    if: ${{ github.event_name == 'push' }}
    # Este job se ejecuta solo si el evento es un push
    # y depende de que el primer job se complete con éxito
    needs: first_job
    runs-on: ubuntu-latest
    env:
      # Variables de entorno que se pueden usar en todo el job
      SALIDA: ${{ needs.first_job.outputs.salida }}

    steps:
      - name: Hola Mundo
        run: echo "$SALIDA"